openapi: 3.0.0
info:
  title: Task Manager API
  contact: {}
  version: '1.0'
servers:
- url: https://dev20todolist.herokuapp.com/api/v1
  variables: {}
paths:
  /task:
    get:
      tags:
      - Task Manager
      summary: Get All Task
      operationId: GetAllTask
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    post:
      tags:
      - Task Manager
      summary: Create Task
      operationId: CreateTask
      parameters: []
      requestBody:
        content:
          application/x-www-form-urlencoded:
            encoding: {}
            schema:
              required:
              - name
              type: object
              properties:
                name:
                  type: string
                  example: Check mail
               
        required: false
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /task/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
        description: The user ID
    get:
      tags:
      - Task Manager
      summary: Get Single Task
      operationId: GetSingleTask
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    delete:
      tags:
      - Task Manager
      summary: Delete Task
      operationId: DeleteTask
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    patch:
      tags:
      - Task Manager
      summary: Update Task
      operationId: UpdateTask
      parameters: []
      requestBody:
        content:
          application/x-www-form-urlencoded:
            encoding: {}
            schema:
              required:
              - name
              - complete
              type: object
              properties:
                name:
                  type: string
                  example: Check mail new
                complete:
                  type: boolean
                  example: true
        required: false
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
tags:
 
- name: Task Manager
  description: ''